### ISSUE TITLE
The system does not resume after clicking the Child's individual display icon ( photo )  on Cars ( Home of the swallow Project )

### ISSUE THREAD

**Issue by k-kay219** [digi-serve/cars_app#21]
### Short Description

After clicking on the icon, the system does not resume, the system is frozen.

### Steps to Reproduce

1. Go to ' Home page of Cars ...'
2. Click on '  the child 's  individual display icon ( photo) ....'
3. the system is frozen  '....'
![หน้าต่าง แรก](https://user-images.githubusercontent.com/100179546/157386583-3bc4384f-d18a-48ca-9547-793482b0507d.jpg)

### Expected Behavior

the user hope  the program should resume well after he clicks on the display icon so that he can add/ edit more detail of the selected child. 

### What Server are you using?

Home page of Cars

### Screenshots

![หน้าต่าง แรก](https://user-images.githubusercontent.com/100179546/157386619-58955079-6ab3-409c-ae3b-8caa58d6c30a.jpg)

********** Ps. On the Screenshot that I attached was not the real Screenshot from Home of the swallow's Cars account ******)

**Comment by jamesduncan** [comment]
This might be fixed with the latest code on V2...so when we are ready to update that server I will do the work to update and then we can test again.

**Comment by jamesduncan** [comment]
I realized this wasn't v2 but v1 but still we hadn't updated code in 4 months on that server so I updated code...I then checked and it was still getting a page unresponsive error. The reason was someone flagged the main Children datacollection to be loadAll...and there were just to many kids and to man relations to handle. I unchecked it but will ask around to see why that may have been done. K can you have them verify it is usable again?
